version: '3.7'

services:
  app: 
    build: .
    container_name: Oncoclinicas_API
    command: yarn start
    ports: 
      - '3000:3000'
    volumes:
      - .:/usr/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
    depends_on:
      - db
  db:
    container_name: Oncoclinicas_MySQL
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp --init-file /data/application/create-database.sql
    restart: always
    ports: 
      - '3306:3306'
    volumes:
        - ./src/database/sql/create-database.sql:/data/application/create-database.sql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=America/Sao_Paulo